version: '3.8'

services:
  mysql:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=timeSheetDevOps
    ports:
    - 3306:3307
  app:
    container_name: timesheet
    restart: unless-stopped
    image: borjinisyrine/devops
    depends_on:
    - mysql
    ports:
    - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql:3307/timeSheetDevOps?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto":"update",
        "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL5Dialect"
        }'